### ISSUE TITLE
add support for jobs with parameters

### ISSUE THREAD

**Issue by magnat** [rafiki270/iJenkins#36]
is it possible to add support for builds with parameters?
i have some jobs where i have to choose a database or somsing like this

**Comment by colons** [comment]
This would be awesome.

**Comment by tompson** [comment]
I started working on this, in the first step I am able to read the build parameters from the job and add the default value to the build request 

next step would be to create a UI asking the user for the parameters before requesting a build

**Comment by rafiki270** [comment]
Best approach would be to create a completely new screen in job management called parameters which would manage any number of these. It would allow anyone to pre-set them and pick one from a list before it builds as you have suggested.

**Comment by colons** [comment]
@rafiki270 build parameters *are* carefully managed presets for builds, and i'm not sure i'm reading you correctly, but it sounds like you're proposing adding presets for choosing selections of these presets, which would be a bad idea

have you looked at what jenkins' own UI for parameterised builds is? other than the fact that the labels for the checkboxes aren't real labels, it's pretty much perfect

**Comment by rafiki270** [comment]
To be honest :) I have never used them which is probably why they are not in the app already. Please feel free to send me some screens on ijenkins@fuerteint.com?

Ondrej

**Comment by rferreira** [comment]
Giving this a bump, it would be a pretty great feature.

**Comment by Moochinius** [comment]
I agree, I have a lot of parameteriaed jobs, using plugins such as, 'Active Choices Plugin', 'Extended Choice Parameter', and the default String Parameter.  It would be greatly beneficial to be able to input values into the build.

**Comment by rafiki270** [comment]
Can you guys com up with some UI structure ... What would be best interface so we can code it someone?

**Comment by rafiki270** [comment]
I am closing this, please feel free to re-open shall you have any nice and elegant solution

**Comment by colons** [comment]
i still don't understand how stealing jenkins' actual parameterised builds UI isn't 'elegant'; you just need to show a list of the options with switches next to them, defaulted to whatever jenkins would have them default to. the whole point is these are settings specifically chosen by the user because they're important and liable to be changed on a per-run basis, nothing more is necessary. you already know that, for a job with parameters, those parameters have been chosen by the user with such a UI in mind.
