### ISSUE TITLE
Can't add Jenkins server https://<server>/jenkins on the list

### ISSUE THREAD

**Issue by matejk** [rafiki270/iJenkins#38]
I wanted to add a Jenkins server that is accessed via HTTPS (port 443) and is listening on the relative path /jenkins.

iJenkins is not able to connect (HTTP code 404). The server URL displayed in iJenkins is server.si/jenkins:443.

I did not find a way to enter the URL in such a way that this server would be added on the list.

**Comment by tammojan** [comment]
I'm experiencing the same issue. Did the merged version make the App store with the April 5 update? (I'm guessing no.)
