### ISSUE TITLE
Jenkins authentication realm GitHub O-Auth

### ISSUE THREAD

**Issue by drscream** [rafiki270/iJenkins#39]
Jenkins support different authentication realms but only one at the same time. I'm using the GitHub O-Auth authentication on my installation. I'm not sure if this a feature that is able to implement into the App itself but it would be nice to support O-Auth realm also.

At the moment I only receive the error that it couldn't be authenticated on my Jenkins server.

**Comment by rafiki270** [comment]
there is another ticket on this that I leave open on this topic
