### ISSUE TITLE
When you have a view that is alphabetically before 'All', iJenkins loads in a weird state

### ISSUE THREAD

**Issue by colons** [rafiki270/iJenkins#42]
We have a view on our Jenkins server with a name that appears alphabetically before 'All'. When iJenkins first loads up, it claims (in the top right corner) to be showing this custom view, but all builds are visible in the list, and the pie chart at the top refers to all builds. While all builds are visible, however, only the builds in the view get fully populated, the rest remain in this weird half-loaded limbo.

**Comment by tammojan** [comment]
Ah that would explain the crippled view I always see (since every build starts with an underscore).

**Comment by rafiki270** [comment]
Unfortunately I won't be in a position to fix this at least for the next month and a half ... If anyone could pick this up that would great otherwise I will fix this later ...

**Comment by tammojan** [comment]
I'll grep the code for "All" and see if a fix is trivial.

**Comment by rafiki270** [comment]
Just a thought but do you have an idea how this will behave in a multilingual environment?

**Comment by tammojan** [comment]
The cause is probably in the following lines in FTServerHomeViewController.m:91 , which selects the first view as a default (and the rest of the logic initializes everything assuming this is 'All'):
```
if (_serverObject.views.count > 1) {
    if (!_selectedView) {
        _selectedView = [_views objectAtIndex:0];
    }
}
```

A solution would be to check if there is a view named 'All' (or any translation).
