### ISSUE TITLE
Issues connecting to a windows instance 

### ISSUE THREAD

**Issue by themaniac27** [rafiki270/iJenkins#47]
I'm having issues trying to connect to a window instance of jenkins.  Is it even possible or does this app only support linux/ios versions of Jenkins.

I'm ping my server ip on my phone so I know my phone can talk to the server.

I have jenkins 1.617 installed on a Windows 2008 R2 VM.
It is listening on port 8080
It is installed in the C:/Jenkins folder
Firewall is currently off.

Here are my parameters in the app
Instance name: mybld09 (I have also tried using the ip address)
Path /
Port 8080

**Comment by themaniac27** [comment]
Ignore my last post.  Just read the first page.  Is it possible to support other OS in the future

**Comment by rafiki270** [comment]
I haven’t tested windows but as iJenkins is connecting to a Jenkins API, I don’t see why it wouldn’t work? … could you please PM me your server url (if it’s not a production obviously) and I can take a look what is wrong with the app. My skype is rafiki270.


> On 27 Aug 2015, at 13:21, themaniac27 <notifications@github.com> wrote:
> 
> Ignore my last post. Just read the first page. Is it possible to support other OS in the future
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/rafiki270/iJenkins/issues/47#issuecomment-135405485>.
> 


-- 
 

*-----------------------------------------------*

*Confidentiality notice*

This communication is from Fuerte Int Ltd, a private limited company 
registered in England and Wales with registered number 07266175 having its 
registered office at THE MANOR HOUSE, 34 LONDON ROAD, NEWBURY, BERKSHIRE, 
ENGLAND, RG14 1JX . 

This electronic message contains information which may be privileged and 
confidential. The information is intended to be for the use of the 
individual(s) or entity named above. If you are not the intended recipient 
be aware that any disclosure, copying, distribution or use of the contents 
of this information is prohibited. If you have received this electronic 
message in error, please notify us by telephone or e-mail as above 
immediately.
